name: CI

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash -l {0}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[tests,dev]"
      
      - name: Lint Python files
        run: |
          find . -name "*.py" | xargs black --check
          find . -name "*.py" | xargs isort --profile black --check-only
          darglint . --strictness=short --ignore-raise=ValueError

      - name: Typecheck with mypy
        run: |
          find fmmax -name "*.py" | xargs mypy
          find examples -name "*.py" | xargs mypy
        
      - name: Run Python tests
        run: |
          python -m pytest