name: run tests

on:
  pull_request:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Setup environment
        run: |
            python -m pip install -e ".[test]"
      
      - name: Lint Python files
        run: |
          find . -name "*.py" | xargs black --check
          find . -name "*.py" | xargs isort --profile black --check-only
        
      - name: Run Python tests
        run: |
          find tests -type d -print0 | xargs -0 -t -n1 python -m unittest discover -p '*_test.py' -s